### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ppstudiosdev** [TheNextLvl-net/worlds#35]
### Describe the bug

.

### To Reproduce

.

### Expected behaviour

.

### Screenshots / Videos

.

### Error log (if applicable)

https://paste.gg/p/anonymous/394cf4a9e4a64a7a964432a892600d80

### Worlds Version

worlds-2.0.0-dev-all.jar

### Checklist

- [X] I am using the newest build from https://github.com/TheNextLvl-net/worlds and the issue still persists.

### Anything else?

.

**Comment by NonSwag** [comment]
Another instance of your server is already using those worlds, or your server crashed and couldn't unlock the worlds.
Delete the session.lock files in your world folders and restart.
