### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by illyrius666** [TheNextLvl-net/worlds#4]
I have some questions about this plugin.
1. do you guys have a discord server?
2. does this plugin have placeholders and integration with PAPI?
3. does this plugin have a system where i can import the worlds config from my worlds?

**Comment by NonSwag** [comment]
1. thenextlvl.net/discord
2. no, unless there is a good use for it, papi support won't come
3. if you want to import world images, you have to use /world import [image]
if you want to import an existing world you have to use /world create [name] (to properly create the world you should define the world type and environment)

Hope that helps.
